using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AtoIndicator.Migrations
{
    public partial class mig1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tradeResult",
                columns: table => new
                {
                    dTradeTime = table.Column<DateTime>(nullable: false),
                    sCode = table.Column<string>(nullable: false),
                    nBuyStrategyIdx = table.Column<int>(nullable: false),
                    nBuyStrategySequenceIdx = table.Column<int>(nullable: false),
                    sType = table.Column<string>(nullable: true),
                    sCodeName = table.Column<string>(nullable: false),
                    nRqTime = table.Column<int>(nullable: false),
                    nBuyEndTime = table.Column<int>(nullable: false),
                    nDeathTime = table.Column<int>(nullable: false),
                    nBuyPrice = table.Column<int>(nullable: false),
                    nDeathPrice = table.Column<int>(nullable: false),
                    nOrderPrice = table.Column<int>(nullable: false),
                    nOriginOrderPrice = table.Column<int>(nullable: false),
                    fProfit = table.Column<double>(nullable: false),
                    nMaxPriceAfterBuy = table.Column<int>(nullable: false),
                    nMaxTimeAfterBuy = table.Column<int>(nullable: false),
                    fMaxPowerAfterBuy = table.Column<double>(nullable: false),
                    nMinPriceAfterBuy = table.Column<int>(nullable: false),
                    nMinTimeAfterBuy = table.Column<int>(nullable: false),
                    fMinPowerAfterBuy = table.Column<double>(nullable: false),
                    nMaxPriceMinuteAfterBuy = table.Column<int>(nullable: false),
                    nMaxTimeMinuteAfterBuy = table.Column<int>(nullable: false),
                    fMaxPowerMinuteAfterBuy = table.Column<double>(nullable: false),
                    nMinPriceMinuteAfterBuy = table.Column<int>(nullable: false),
                    nMinTimeMinuteAfterBuy = table.Column<int>(nullable: false),
                    fMinPowerMinuteAfterBuy = table.Column<double>(nullable: false),
                    nMaxPriceAfterBuyWhile10 = table.Column<int>(nullable: false),
                    nMaxTimeAfterBuyWhile10 = table.Column<int>(nullable: false),
                    fMaxPowerAfterBuyWhile10 = table.Column<double>(nullable: false),
                    nMinPriceAfterBuyWhile10 = table.Column<int>(nullable: false),
                    nMinTimeAfterBuyWhile10 = table.Column<int>(nullable: false),
                    fMinPowerAfterBuyWhile10 = table.Column<double>(nullable: false),
                    nMaxPriceAfterBuyWhile30 = table.Column<int>(nullable: false),
                    nMaxTimeAfterBuyWhile30 = table.Column<int>(nullable: false),
                    fMaxPowerAfterBuyWhile30 = table.Column<double>(nullable: false),
                    nMinPriceAfterBuyWhile30 = table.Column<int>(nullable: false),
                    nMinTimeAfterBuyWhile30 = table.Column<int>(nullable: false),
                    fMinPowerAfterBuyWhile30 = table.Column<double>(nullable: false),
                    nMaxPriceAfterBuyWhile60 = table.Column<int>(nullable: false),
                    nMaxTimeAfterBuyWhile60 = table.Column<int>(nullable: false),
                    fMaxPowerAfterBuyWhile60 = table.Column<double>(nullable: false),
                    nMinPriceAfterBuyWhile60 = table.Column<int>(nullable: false),
                    nMinTimeAfterBuyWhile60 = table.Column<int>(nullable: false),
                    fMinPowerAfterBuyWhile60 = table.Column<double>(nullable: false),
                    isAllBuyed = table.Column<bool>(nullable: false),
                    isAllSelled = table.Column<bool>(nullable: false),
                    fStartGap = table.Column<double>(nullable: false),
                    nBuyVolume = table.Column<int>(nullable: false),
                    fPowerWithOutGap = table.Column<double>(nullable: false),
                    fPower = table.Column<double>(nullable: false),
                    fPlusCnt07 = table.Column<double>(nullable: false),
                    fMinusCnt07 = table.Column<double>(nullable: false),
                    fPlusCnt09 = table.Column<double>(nullable: false),
                    fMinusCnt09 = table.Column<double>(nullable: false),
                    fPowerJar = table.Column<double>(nullable: false),
                    sBuyStrategyName = table.Column<string>(nullable: true),
                    sSellStrategyMsg = table.Column<string>(nullable: true),
                    nTradeCnt = table.Column<int>(nullable: false),
                    nChegyulCnt = table.Column<int>(nullable: false),
                    nHogaCnt = table.Column<int>(nullable: false),
                    nNoMoveCnt = table.Column<int>(nullable: false),
                    nFewSpeedCnt = table.Column<int>(nullable: false),
                    nMissCnt = table.Column<int>(nullable: false),
                    lTotalTradeVolume = table.Column<long>(nullable: false),
                    lTotalBuyVolume = table.Column<long>(nullable: false),
                    lTotalSellVolume = table.Column<long>(nullable: false),
                    nAccumUpDownCount = table.Column<int>(nullable: false),
                    lTotalTradePrice = table.Column<long>(nullable: false),
                    lTotalBuyPrice = table.Column<long>(nullable: false),
                    lTotalSellPrice = table.Column<long>(nullable: false),
                    lMarketCap = table.Column<long>(nullable: false),
                    nAccumCountRanking = table.Column<int>(nullable: false),
                    nMarketCapRanking = table.Column<int>(nullable: false),
                    nPowerRanking = table.Column<int>(nullable: false),
                    nTotalBuyPriceRanking = table.Column<int>(nullable: false),
                    nTotalBuyVolumeRanking = table.Column<int>(nullable: false),
                    nTotalTradePriceRanking = table.Column<int>(nullable: false),
                    nTotalTradeVolumeRanking = table.Column<int>(nullable: false),
                    nTotalRank = table.Column<int>(nullable: false),
                    nMinuteTotalRank = table.Column<int>(nullable: false),
                    nMinuteTradePriceRanking = table.Column<int>(nullable: false),
                    nMinuteTradeVolumeRanking = table.Column<int>(nullable: false),
                    nMinuteBuyPriceRanking = table.Column<int>(nullable: false),
                    nMinuteBuyVolumeRanking = table.Column<int>(nullable: false),
                    nMinutePowerRanking = table.Column<int>(nullable: false),
                    nMinuteCountRanking = table.Column<int>(nullable: false),
                    nMinuteUpDownRanking = table.Column<int>(nullable: false),
                    nFakeBuyCnt = table.Column<int>(nullable: false),
                    nFakeAssistantCnt = table.Column<int>(nullable: false),
                    nFakeResistCnt = table.Column<int>(nullable: false),
                    nPriceUpCnt = table.Column<int>(nullable: false),
                    nPriceDownCnt = table.Column<int>(nullable: false),
                    nTotalFakeCnt = table.Column<int>(nullable: false),
                    nTotalFakeMinuteCnt = table.Column<int>(nullable: false),
                    nUpCandleCnt = table.Column<int>(nullable: false),
                    nDownCandleCnt = table.Column<int>(nullable: false),
                    nUpTailCnt = table.Column<int>(nullable: false),
                    nDownTailCnt = table.Column<int>(nullable: false),
                    nShootingCnt = table.Column<int>(nullable: false),
                    nCandleTwoOverRealCnt = table.Column<int>(nullable: false),
                    nCandleTwoOverRealNoLeafCnt = table.Column<int>(nullable: false),
                    fSpeedCur = table.Column<double>(nullable: false),
                    fHogaSpeedCur = table.Column<double>(nullable: false),
                    fTradeCur = table.Column<double>(nullable: false),
                    fPureTradeCur = table.Column<double>(nullable: false),
                    fPureBuyCur = table.Column<double>(nullable: false),
                    fHogaRatioCur = table.Column<double>(nullable: false),
                    fSharePerHoga = table.Column<double>(nullable: false),
                    fSharePerTrade = table.Column<double>(nullable: false),
                    fHogaPerTrade = table.Column<double>(nullable: false),
                    fTradePerPure = table.Column<double>(nullable: false),
                    nDownCntMa20m = table.Column<int>(nullable: false),
                    nDownCntMa1h = table.Column<int>(nullable: false),
                    nDownCntMa2h = table.Column<int>(nullable: false),
                    nUpCntMa20m = table.Column<int>(nullable: false),
                    nUpCntMa1h = table.Column<int>(nullable: false),
                    nUpCntMa2h = table.Column<int>(nullable: false),
                    fMSlope = table.Column<double>(nullable: false),
                    fISlope = table.Column<double>(nullable: false),
                    fTSlope = table.Column<double>(nullable: false),
                    fHSlope = table.Column<double>(nullable: false),
                    fRSlope = table.Column<double>(nullable: false),
                    fDSlope = table.Column<double>(nullable: false),
                    fMAngle = table.Column<double>(nullable: false),
                    fIAngle = table.Column<double>(nullable: false),
                    fTAngle = table.Column<double>(nullable: false),
                    fHAngle = table.Column<double>(nullable: false),
                    fRAngle = table.Column<double>(nullable: false),
                    fDAngle = table.Column<double>(nullable: false),
                    nCrushCnt = table.Column<int>(nullable: false),
                    nCrushUpCnt = table.Column<int>(nullable: false),
                    nCrushDownCnt = table.Column<int>(nullable: false),
                    nCrushSpecialDownCnt = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tradeResult", x => new { x.dTradeTime, x.sCode, x.nBuyStrategyIdx, x.nBuyStrategySequenceIdx });
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "tradeResult");
        }
    }
}
